name: conquer-util tests
on:
  push:
    branches: [ master ]
    tags: [ v0.* ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
      - run: cargo test --features nightly