name: Rust

on:
  push:
    branches: [ master ]
    tags: [ v0.* ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        rust: [ nightly ]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (w/ nightly feature)
      run: cargo test --verbose --features nightly